apiVersion: v1
kind: Service
metadata:
  name: jenkins-instance-service
spec:
  type: NodePort
  selector:
    app: jenkins-instance
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085  # İstediğin bir port, 30000-32767 arasında olmalı
